// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nllskphszfwiegidzyix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sbHNrcGhzemZ3aWVnaWR6eWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQ5NzcsImV4cCI6MjA2NTU1MDk3N30.mSGjAMBGeQkeEq0T9zWbT_nva45nme1-naau8wI9MO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);